qld-gov-au/ckan-qld-infrastructure

requirements-dev.txt
templates/Salsa-CKAN-Extensions.cfn.yml
vars/shared-OpenData.var.yml

- Added `ckanext-harvest` to `requirements-dev.txt`
- Added HarvestExtension settings to `templates/Salsa-CKAN-Extensions.cfn.yml`
- Added `CKANExtHarvest` to `vars/shared-OpenData.var.yml`
cc: @duttonw & @ThrawnCA

[DQL2-13] CKAN Harvest - Install and configure

---

.ahoy.yml
.circleci/config.yml
.circleci/test.sh
.docker/Dockerfile.ckan
.docker/scripts/create-test-data.sh
.docker/scripts/init-ext.sh
.docker/scripts/init.sh
.docker/scripts/serve.sh
.github/workflows/test.yml
docker-compose.yml
test/features/navigation.feature
test/features/steps/steps.py

Sync CI config with theme repo (which is working).

QOL-8048 Fix integration tests

---

vars/database.var.yml
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

Update Open Data theme to fix Pylons routing

Develop to master

---

vars/CKAN-Stack.var.yml

- fix logging parameters when retrieving filesystem metadata
- fix null check on has_more_facets

[QOL-8120] update CKAN fork to fix bugs

---

vars/CKAN-Stack.var.yml
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

- Update S3 filestore extension to support automatic visibility and more robust handling of missing files
- Update cookbook to enable automatic visibility

QOL-8179 S3 unsigned urls

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

This should not impact DEV at all, it's just being merged for tidiness.

[QOL-8343] update ckanext-data-qld to patch Salsa work

---

check_ext_versions.py
get_latest_tag.sh

- This won't detect untagged changes in extensions, but it's a start toward making sure work isn't missed in a release

Add script to check whether infrastructure is using latest tags

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

- Don't reuse old resource cache after the resource is updated

[QOL-8179] update s3filestore to fix caching

---

vars/CKAN-Stack.var.yml

Opening pull request directly to master since the version increment makes no difference to DEV (it's using a branch, not a tag).

[QOL-8406] update cookbook to fix Solr health checks

---

vars/CKAN-Stack.var.yml

- mod_lua and other unnecessary modules are being stripped out

[QOL-8537] update cookbook to remove Apache vulnerability

---

vars/CKAN-Stack.var.yml

Revert to using 'paster' for now so we have automatic authentication. Need to find another solution for CKAN 2.9

[DC-28671] update cookbook to fix broken email notifications

---

.docker/Dockerfile.ckan
.docker/scripts/ckan_cli
.docker/scripts/create-test-data.sh
.docker/scripts/doctor.sh
.docker/scripts/init.sh
.docker/scripts/serve.sh
.docker/test-OpenData.ini
.github/workflows/test-staging.yml
test/features/comments.feature
test/features/config.feature
test/features/data_request.feature
test/features/data_validation.feature
test/features/dataset_deletion.feature
test/features/engagement_reporting.feature
test/features/resource_availability.feature
test/features/steps/steps.py
test/features/user_creation.feature
vars/CKAN-Stack.var.yml
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

- Patch organisation links
- Merge theme into ckanext-data-qld

QOL-7939 Update ckanext-data-qld

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

https://github.com/qld-gov-au/ckanext-harvester-data-qld-geoscience/releases/tag/v0.0.3

Update geoscience version

---

test/features/data_usability_rating.feature
vars/CKAN-Stack.var.yml
vars/shared-CKANTest.var.yml

- Configure Geoscience Harvester
- Handle CKAN 2.9 email notifications

QOL-8576 update cookbook

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- restore the fields for Data Request Closing Circumstances

[QOL-7939] update ckanext-data-qld to fix admin config

---

vars/CKAN-Stack.var.yml

- Handle large Solr indexes
- Remove Apache PHP module

[QOL-8537][QOL-8775] update cookbook

---

test/features/comments.feature
test/features/config.feature
test/features/data_qld_theme.feature
test/features/search_facets.feature
test/features/steps/steps.py
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Provide the URLs that Squiz needs to properly render the homepage and /article pages.

Qol 8779 update ckanext-data-qld to fix Squiz compatibility

---

vars/CKAN-Stack.var.yml

- fix email notification script for CKAN 2.8
- fix Cloudwatch metrics for CKAN 2.9
- make algorithm for picking 'active' job server more robust

[QOL-8576] update cookbook to fix errors in scheduled jobs

---

vars/shared-Publications.var.yml

- fix resource modified timestamp
- make notification email bodies match Open Data

[QOL-8608][DC-30092] update Publications theme

---

vars/shared-Publications.var.yml

Increment to ckanext-publications-qld-theme to 1.1.2
https://github.com/qld-gov-au/ckanext-publications-qld-theme/releases/tag/1.1.2

QOL-8857 DC-31575 add updated publications theme

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

- Update ckanext-data-qld to fix report links and nature_of_change handling
- Update ckanext-csrf-filter to fix handling of slashes

DC-31541 API mandatory fields

---

.ahoy.yml
.docker/scripts/ckan_cli
.docker/scripts/create-test-data-OpenData.sh
.docker/scripts/create-test-data-Publications.sh
.docker/scripts/create-test-data.sh
.docker/test-OpenData.ini
.github/workflows/test.yml
test/features/admin_reporting.feature
test/features/config.feature
test/features/data_qld_theme.feature
test/features/data_request.feature
test/features/datasets.feature
test/features/engagement_reporting.feature
test/features/homepage.feature
test/features/login.feature
test/features/resource_freshness.feature
test/features/steps/steps.py
test/features/user_creation.feature
test/features/users.feature
vars/CKAN-Stack.var.yml
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

- Fix PURL integration under CKAN 2.9
- Restore custom 'robots.txt'
- Add help text for 'Excluded display name words'
- Fix activity stream browsing
- Sync scenario tests

[DC-31965][QOL-8988][QOL-8978] update ckanext-data-qld and ckanext-qgov

---

requirements-dev.txt
vars/CKAN-Stack.var.yml

- add cron job to purge Beaker session cache files
- change Beaker session storage backend to Redis so it's cleaned up automatically
- set extension ordering so sysadmin config page renders correctly

[DC-32168][QOL-8978] update cookbook

---

vars/shared-Publications.var.yml

- Drop duplicate breadcrumbs
- Fix activity stream links
- Restore custom robots.txt file

[DC-31965][QOL-8976][QOL-8989] update Publications theme

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

Use release version instead of a commit hash.

Develop to master - update Harvest

---

vars/database.var.yml

- This should be tested thoroughly before advancing further. If it works, we can then test 13. Easier to try one version at a time than to downgrade.

[QOL-9344] update DEV to PostgreSQL 12

---

vars/database.var.yml

- This should be tested thoroughly before advancing further.

[QOL-9344] update DEV to PostgreSQL 13

---

.docker/Dockerfile-template.ckan
vars/database.var.yml

- Can't update multiple major versions at once

[QOL-9344] use PostgreSQL 12 for higher environments

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

- Path to the base FriendlyFormPlugin has changed

[QOL-9385] update CSRF filter to fix Login CSRF handling on CKAN 2.9

---

templates/cloudfront.cfn.yml.j2

also enable:
* http2and3 protocol
* auto compress
* ip6 support

QOL-9408 Update cloudfront to group squiz cms behaviour, update to new cache behaviour standard

---

.github/workflows/test-staging.yml
.github/workflows/test.yml
templates/cloudfront.cfn.yml.j2
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

Remove logging
Allow theme includes from cms without version hash
Fix email notifications.

Increment extensions

---

templates/cloudfront.cfn.yml.j2
vars/cloudfront.var.yml
vars/shared-OpenData.var.yml

This is a hotfix for google analytics issue in data-qld theme as well as increase in waiting for server response time.

Data qld theme patch, increase timeout on waiting on server

---

vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

To allow PARQUET file format uploads

QOLSVC-485 increment ckanext-resource-type-validation to 1.0.5

---

vars/CKAN-Stack.var.yml
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

Update ckanext-validation and sync CKANTest sandbox with Open Data.

QOLSVC-571 link digital updates

---

templates/3_tier_vpc.yml

to ensure HA occurs if AZ a is down as well as reduce cross az costs

QOLSVC-1161 Enable Nat Gateway per AZ 

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

- Don't cache the login page in case it contains a form token

[QOLSVC-1241] update CSRF filter to fix re-login

---

vars/shared-CKANTest.var.yml

- This includes several fixes for proper testing

[QOLDEV-367] update test CKAN to 2.10 fork

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Also do some CKAN 2.10 prep work, but not fully ready yet

[QOLSVC-1879] update Data theme to fix resource formats

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

Comments will now be searchable (searching for comment text will locate the dataset it's in).

[CHDEXCHAE-64] update YTP Comments to fix comment indexing

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

Add functions for CKAN 2.10 plugin interface

[QOLDEV-316] update Resource Type Validation plugin for CKAN 2.10

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Disable type guessing on existing resources, since the columns should be already guessed
- Disable type guessing on very large resources as they need to load quickly

[QOLDEV-490] update XLoader to use faster loading

---

test/features/dataset_deletion.feature
test/features/steps/steps.py
test/features/user_creation.feature
test/features/users.feature
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

- Apply upstream 2.10.1 fixes
- Add reCAPTCHA support

[QOLDEV-455] update test CKAN 2.10 instance

---

.ahoy.yml
bin/create-test-data.sh
docker-compose.yml
test/features/data_qld_theme.feature
test/features/resources.feature
test/features/steps/steps.py
vars/CKAN-Stack.var.yml
vars/shared-CKANTest.var.yml
vars/shared-Publications.var.yml

- Tooltips will preserve full names

[QOLSVC-2447] update CKAN to add tooltips on truncated links

---

.ahoy.yml
.env
.github/workflows/test-staging.yml
.github/workflows/test.yml
.gitignore
bin/docker-compose.sh
bin/doctor.sh
bin/process-artifacts.sh
test/features/resource_availability.feature
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Preserve full link names, either as link text or as title text.
- Also fix performance of searching data request comments.

QOLSVC-2447 update Open Data theme to fix truncated resource breadcrumbs

---

vars/CKAN-Stack.var.yml

- Don't skip rows that contain empty cells

[QOLSVC-3084] update CKAN fork to fix datastore JSON export

---

.ahoy.yml
.github/workflows/test.yml
bin/serve.sh
test/features/comments.feature
test/features/datarequest_circumstances.feature
test/features/engagement_reporting.feature
test/features/resource_align_default_schema.feature
test/features/resource_availability.feature
test/features/resource_privacy_assessment_result.feature
test/features/schema_generation.feature
test/features/steps/steps.py
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

Also update associated scenario tests to handle both old and new CKAN.

QOLDEV-312 update Open Data theme to prepare for CKAN 2.10

---

bin/init-ext.sh
vars/shared-OpenData.var.yml

- Don't set the 'force-reinstall' flag as it's unsuccessfully attempting to replace system 'six'

[QOLSVC-978] restore ckanext-scheming app definition and fix install

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Prepare for CKAN 2.10
- Drop validation reports when schema no longer exists

[QOLDEV-323] update Validation plugin

---

vars/shared-CKANTest.var.yml

- We need the app definition so that the cookbook will add it to the config

[QOLSVC-978] restore ckanext-scheming to CKANTest sandbox

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

- Provide a User-Agent definition so Bing will respect the robots file

[QOLDEV-610] update Publications theme to fix robots config

---

vars/CKAN-Stack.var.yml

- Always configure the new database index to allow non-unique addresses, previous syntax didn't work

[QOLSVC-978] update CKAN fork to fix non-unique emails

---

vars/CKAN-Stack.var.yml

- Issues with Solr 8 have been identified and addressed, upgrade can proceed now

[QOLDEV-627] upgrade to Solr 8 again

---

vars/CKAN-Stack.var.yml

- Move Solr backups inside Solr home directory for compatibility with Solr 8+ restrictions.

Develop to master - update cookbook

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

- Fix revocation of API tokens via web interface
- Add support for the SameSite attribute on the token cookie
- Add support for custom whitelist rules, defining URLs that will not be checked
- Fix handling of response streams, which can't have tokens injected

[QOLSVC-3186] update CSRF filter

---

vars/CKAN-Stack.var.yml

- Fix missing dollar sign in variable reference
- Add compatibility JAR to Lucene check so we can handle indexes created by an older version

[QOLDEV-627] update cookbook to fix Solr replication

---

vars/shared-Publications.var.yml

- Hide size field when uploading files as it will be automatically determined
- Apply link styling to buttons with the 'btn-link' class

[QOLDEV-640][QOLSVC-3826] update Publications theme

---

vars/CKAN-Stack.var.yml
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Allow empty string for file size
- Don't apply url validation to uploaded files

[QOLDEV-667][QOLSVC-3826] Fix uploader issues

---

test/features/steps/steps.py
vars/CKAN-Stack.var.yml
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Allow empty string for file size
- Don't apply url validation to uploaded files

Develop - [QOLDEV-667][QOLSVC-3826] Fix uploader issues

---

opsworks-deploy.sh
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

Increase deployment timeout from 15 to 30 minutes, as the most recent deployment to DEV took 20 minutes

[QOLSVC-4191] Increase deployment timeout from 15 to 30 minutes

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

- Fix SameSite attribute on Python 2
- Exclude _logout URL from filtering

[QOLSVC-3914] patch CSRF filter

---

check_ext_versions.py
get_latest_tag.sh
vars/CKAN-Stack.var.yml

- Pin the Click dependency version so both plugins will work.

QOLDEV-684 update cookbook to fix QA and Validation plugins coexisting

---

vars/CKAN-Stack.var.yml

- Also fix deployment errors caused by trying to update ownership on Solr snapshots that have been deleted

[QOLSVC-4126] update cookbook to use working maps provider

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Replace dicts with strings before indexing. This is covered by the QGOV CKAN fork, but won't be merged upstream, so should be fixed at the source. https://github.com/ckan/ckan/issues/7779

[QOLDEV-329] update QA plugin

---

test/features/users.feature
vars/CKAN-Stack.var.yml

- GitHub issue #7980 on ckan/ckan

[QOLDEV-692] update CKAN core to fix activity streams containing organisation entries

---

templates/database.cfn.yml

- This primarily affects the COPY command used by XLoader

[QOLDEV-708] configure PostgreSQL to prefer day-first dates

---

vars/CKAN-Stack.var.yml

- Fix syntax so Solr snapshots will be excluded when updating ownership of Solr directories

[QOLDEV-627] update cookbook to fix Solr deployments

---

vars/CKAN-Stack.var.yml

- Don't load JSON blobs unless necessary

[QOLSVC-4446] update CKAN core to improve activity stream loading time

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

- Rework the templates to inherit as much as possible instead of rewriting the whole page, so we automatically include the email notifications checkbox.

[QOLSVC-4096] update themes to fix user edit page

---

templates/Datashades-OpsWorks-CKAN-Stack.cfn.yml.j2
vars/CKAN-Stack.var.yml

- Custom JSON is a feature that will remain available in Chef even without OpsWorks

[QOLDEV-545] add app sources to OpsWorks custom JSON

---

.gitignore
build-CKAN.sh
chef-deploy.sh
chef-json.yml
templates/chef-source.json.j2
templates/chef.json.j2
vars/CKAN-Stack.var.yml

- This can be used to run Chef recipes via Systems Manager

[QOLDEV-545] add Ansible playbook to generate Chef custom JSON for stack

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Skip blank lines
- Ignore blank cells beyond the number of columms (which can be generated by Excel)
- Fall back to direct load if Tabulator initially fails (in case the error was from type guessing failure)

[QOLSVC-5123] update XLoader to handle imperfect files more robustly

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Pin tableschema dependency to preserve Py2 support

[QOLCHG-538] update Validation Schema Generator

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

- Don't log dicts that might contain passwords

[QOLSVC-4988] update S3 Filestore plugin

---

vars/CKAN-Stack.var.yml
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

- Update s3filestore to prevent passwords from being logged
- Update validation schema generator to fix Py2 compatibility

Develop to master - patch plugins

---

vars/CKAN-Stack.var.yml

- Make null check on 'size' field more robust

[QOLDEV-749] update CKAN fork to fix data tables view

---

vars/CKAN-Stack.var.yml

- Fix Recline previews
- Manage Solr via Supervisord instead of initd or systemd, for greater consistency
- Use Parameter Store values instead of custom JSON, so we can run commands on server start without an active deployment

[QOLDEV-545] update cookbook

---

dev-requirements.txt
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

- Treat PPT and PPTX files as interchangeable

[QOLSVC-5373] update Resource Type Validation plugin

---

templates/hosted-zone.cfn.yml
vars/CKAN-Stack.var.yml

- Ensure all values are made available in time for deployments to use them

[QOLDEV-818] update cookbook to fix reliance on Parameter Store

---

templates/Datashades-OpsWorks-CKAN-Stack.cfn.yml.j2

- This will allow us to connect autoscaling events
- Also clean up the obsolete OpsWorks app definitions for CKAN and Solr

[QOLDEV-817] add an SNS topic to trigger the deployment function

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Restart sequences when truncating tables

[QOLSVC-5551] update XLoader to preserve datastore IDs

---

templates/Datashades-OpsWorks-CKAN-Stack.cfn.yml.j2

- This has invalid syntax and hasn't turned out to be the chosen approach

[QOLDEV-817] drop obsolete SNS topic associated with Lambda

---

templates/Datashades-OpsWorks-CKAN-Instances.cfn.yml.j2
vars/instances-OpenData.var.yml

- This should be able to speed up instance start by partially setting up instances in advance

[QOLDEV-833] use custom AMI as a basis for Open Data web instances

---

chef-deploy.sh

- Instances should be handled by health checks once deployment finishes, and replaced if needed

[QOLDEV-818] pull instances out of standby even if deployment fails

---

vars/CKAN-Stack.var.yml
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Adjust requirement files to avoid conflicts between plugins
- Drop unnecessary installation steps

[QOLDEV-545] update cookbook and plugins for cleaner deployments

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Need newer Python before we can update 'validators'

[QOLCHG-590] update QA plugin to revert Snyk patch we're not ready for

---

templates/Datashades-OpsWorks-CKAN-Instances.cfn.yml.j2

- Shared yum packages are preinstalled, 4GB swapfile has been created, Supervisord service enabled. No environment-specific changes have been made.

[QOLDEV-833] use bare-bones custom AMI

---

chef-deploy.sh
templates/Datashades-OpsWorks-CKAN-Instances.cfn.yml.j2
vars/instances-CKANTest.var.yml
vars/instances-OpenData.var.yml
vars/instances-Publications.var.yml

Also add more documentation comments on our AMI IDs.

QOLDEV-892 update Chef client and improve handling of instances already in Standby

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Custom usability scores were broken by CKAN 2.10 upgrade

[QOLDEV-915] update Data theme plugin to fix integration with QA

---

vars/CKAN-Stack.var.yml

- Import by stopping the instance and doing a full index replacement rather than try a live import

[QOLDEV-863] update cookbook to fix Solr replication

---

vars/CKAN-Stack.var.yml

Update cookbook to use more robust Solr replication method.

Develop to master - fix Solr HA

---

chef-deploy.sh

- Lower the threshold for instances to be replaced, so replacing many instances is faster
- Extend the maximum allowed time for an instance refresh

[QOLDEV-920] speed up instance refreshes

---

vars/CKAN-Stack.var.yml

- Continue if there were no previous index files to remove
- Skip malformed snapshot archives

[QOLDEV-863] update cookbook to make Solr sync more robust

---

vars/database.var.yml

- DEV has been running on 13 with no issues for many months

[QOLSVC-7171] update higher environments to PostgreSQL 13

---

vars/database.var.yml

- 15 is the target, but we should only upgrade through one major version at once

[QOLSVC-7171] update DEV to PostgreSQL 14

---

templates/Datashades-OpsWorks-CKAN-Instances.cfn.yml.j2

- 'if' markup is eating the trailing line break and disrupting the syntax, so refactor it to assign and output a variable

[QOLSVC-7469] fix disk size syntax

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

- Use correct 'user edit' schema, not the default user schema (password is optional)

[QOLDEV-935] update QGOV plugin to fix sysadmin management via web UI

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

https://github.com/qld-gov-au/ckanext-data-qld/releases/tag/7.2.13

QOLSVC-6875 update version on ckanext-data-qld to 7.2.13

---

templates/database.cfn.yml

- This is strongly recommended by Amazon, https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.Autovacuum.html

[QOLSVC-7171] enable RDS autovacuum

---

vars/CKAN-Stack.var.yml
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

- Insert blank for missing parameters, or allow a default value to be specified

[QOLDEV-933] update SSM Config plugin

---

vars/CKAN-Stack.var.yml
vars/shared-CKANTest.var.yml

- Update sandbox plugin version
- Update cookbook to provide SSO config

QOLSVC-5478 update SSO plugin

---

vars/database.var.yml

- Testing on DEV was successful

[QOLSVC-7171] update all environments to PostgreSQL 15

---

.docker/test-OpenData.ini
.docker/test-Publications.ini
test/features/steps/steps.py
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml
vars/shared-Publications.var.yml

Need to ensure we have added credentials to SSM Parameter Store before this goes to production. Staging parameters are ready.

[QOLSVC-5478] enable SSO plugin for all environments

---

templates/waf_web_acl.cfn.yml
test/features/xloader.feature

- Allow up to 1000 requests per minute, to be revised as needed

[QOLSVC-7642] throttle request rates from the same IP address

---

.github/workflows/test-staging.yml
.github/workflows/test.yml
bin/init-OpenData.sh
vars/CKAN-Stack.var.yml

- Remove obsolete MoG redirects
- Enable all XLoader status badges

[QOLDEV-1006] update cookbook

---

.ahoy.yml
.docker/Dockerfile-template.ckan
bin/create-test-data-OpenData.sh
bin/create-test-data-Publications.sh
bin/create-test-data.sh
bin/docker-compose.sh
bin/init-ext.sh
bin/init.sh
bin/serve.sh
docker-compose.yml
test/features/data_usability_rating.feature
test/features/steps/steps.py
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

Also update the sandbox environment so we can do manual testing

QOLDEV-954 start updating plugins for CKAN 2.11

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Merge upstream changes
- Drop Python 2 including CKAN 2.8

[QOLDEV-987] update Archiver to handle CKAN 2.11

---

vars/CKAN-Stack.var.yml
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

Also update CKAN fork to add CAPTCHA to login error messages.

QOLDEV-1075 update Harvest for CKAN 2.11

---

vars/CKAN-Stack.var.yml

This will allow us to drop the changed message from ckanext-qgov

[QOLDEV-955] update CKAN fork to include CAPTCHA in login failure messages

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Drop Frictionless, use standard 'csv' module for type sniffing

[QOLDEV-1015] update QA plugin to reduce dependency conflicts

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Handle non-backward-compatible changes in other plugins, preparing for CKAN 2.11

[QOLDEV-1014] update Data theme

---

test/features/steps/steps.py
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- This now includes our User-Agent customisation, so our fork is not necessary.

[QOLDEV-1075] return to upstream Harvest plugin

---

vars/CKAN-Stack.var.yml

- This patches high-priority CVE-2025-24372

[QOLDEV-1087] update CKAN to 2.10.7 base

---

templates/cloudfront.cfn.yml.j2

This is to add datastore readonly caching for up to 1minute, improve cms cache behaviour

QOLSVC-8937 cache corrections

---

inventory/hosts
templates/AMI-Template-Instances.cfn.yml.j2
templates/Datashades-OpsWorks-CKAN-Instances.cfn.yml.j2

- Move hardcoded Jinja values into template parameters
- Update AMI baseline (current baseline image is no longer visible in catalog)

QOLDEV-1068 Cleanup

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Improve admin report query logic for much faster export generation

[QOLDEV-293] update Open Data plugin to speed up report exports

---

.docker/Dockerfile-template.ckan
vars/CKAN-Stack.var.yml

- Apply QGOV customisations to the updated 2.11.3 base
- Add recent UI fixes to improve the appearance of the 'Add new resource' button and the resource 'Manage' button

[QOLSVC-10616] update DEV environments to CKAN 2.11.3 base with UI patches

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Merge upstream 2.x changes
- Trigger type guessing after incompatible file structure changes

[QOLDEV-1141] update XLoader

---

vars/CKAN-Stack.var.yml

- Fix incorrect variable name and missing Solr sync schedule

[QOLSVC-10241] patch cookbook

---

vars/CKAN-Stack.var.yml
vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Replace obsolete GA360 code with GA4

QOLSVC-10984 Google Analytics update

---

.ahoy.yml
test/features/google_analytics.feature
vars/CKAN-Stack.var.yml

- Rework Solr sync to fail over more reliably and recover better
- Reduce multithreading to work around race conditions

[QOLSVC-11279] update cookbook

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Preserve Data Dictionary when types have changed but field names have not.
- Sync changes from upstream

[QOLSVC-11908] update XLoader to improve Data Dictionary

---

vars/shared-CKANTest.var.yml
vars/shared-OpenData.var.yml

- Enable usage of multiple job queues, routing tasks for the same package to the same queue to minimise lock contention
- Fix cleanup of temporary files that go unused due to unchanged files

[QOLSVC-4633] update XLoader
