- vars/CKAN-Stack.var.yml
This allows us to drop the IMiddleware kludge from ckanext-data-qld and prepare for CKAN 2.9.
> [QOL-7939] update CKAN fork to make the post-password-reset landing page configurable

- vars/database.var.yml
- STAGING gets a miniscule cost reduction but is no longer reliant on burst credits.
- PROD gets a slightly larger cost reduction and should get a performance boost.
> [QOL-8025] migrate PROD and STAGING to m6g instances

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- vars/shared-Publications.var.yml
Update themes to exclude pre-signed S3 URLs from indexing in `robots.txt`.
> QOL-8104 exclude S3 from search indexing

- build-CKAN.sh
- build-CKANTest.sh
- build-OpenData.sh
- build-Publications.sh
- opsworks-deploy.sh
- templates/Datashades-OpsWorks-CKAN-Instances.cfn.yml.j2
...if there are spare instances available.
Extra instances in the layer will be started before deploying, then shut down afterward. This should allow deployments without downtime.
> [QOL-8060] adjust deployment steps to make Solr deployments zero-downtime

- templates/Datashades-OpsWorks-CKAN-Instances.cfn.yml.j2
We want to control it manually during deployments.
> [QOL-8060] don't make the secondary Solr instance auto-scale

- templates/Datashades-OpsWorks-CKAN-Instances.cfn.yml.j2
- vars/CKAN-Stack.var.yml
The secondary Solr instance is meant to be manually controlled during deployments, so it shouldn't auto-scale.
> Develop to master

- templates/Datashades-OpsWorks-CKAN-Stack.cfn.yml
- scale up for high memory utilisation, not just high CPU, since memory is more often our bottleneck
> [DC-22275] add memory thresholds to auto-scaling

- vars/shared-CKANTest.var.yml
test-dev.data.qld.gov.au fails without this.
> [QOL-7544] apply our patches to test environment CKAN

- .docker/scripts/create-test-data.sh
- .docker/test-OpenData.ini
- .docker/test-Publications.ini
- .github/workflows/test.yml
- docker-compose.yml
- test/features/login_redirect.feature
- test/features/steps/steps.py
- test/features/user_creation.feature
- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- vars/shared-Publications.var.yml
This allows us to drop the ckanext-data-qld extension from Publications, so it won't be affected by Data-specific features.
> [QOL-8595] update ckanext-qgov to take over shared functions from ckanext-data-qld

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- vars/shared-Publications.var.yml
- reduce task size in memory
- skip updated packages if privacy is unchanged
- add features to hide and delete non-current S3 objects
- degrade instead of breaking if Redis has errors
- strip double quotes from ETag values so Newrelic doesn't choke
- increase cache length for unsigned URLs
> [QOL-8612] update S3 filestore extension

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- also patch YTP Comments to not rely on other extensions, and update CKAN Test environment to have more useful versions in preparation for CKAN 2.9
> [CHG-11299] fix Validation extension version

- vars/shared-CKANTest.var.yml
Update base from 2.9.4 to 2.9.5 and reapply needed patches.
This should add Solr 8 support.
It also adds an option for restricting uploaded MIME types, similarly to ckanext-resource-type-validation but without the same emphasis on ensuring that formats and filenames and sniffed types are compatible. It may be worth incorporating these new config options into that extension.
> [QOL-7544] update test CKAN to be based on more recent upstream

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- vars/shared-Publications.var.yml
Since this only alters the version numbers for environments above DEV, merging it to 'develop' makes no difference.
> [QOL-8612] update ckanext-s3filestore to fix migration of legacy resources

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- vars/shared-Publications.var.yml
- move maintainer vs author logic into Data-specific extension as Publications keeps these fields separate
- fix organisation read links
- fix mandatory fields appearing in API
- add in-page DCTERMS metadata
> [QOL-8842][QOL-8856][QOL-8857] update ckanext-data-qld to fix bugs

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
Ignore 'nature_of_change' and 'next_update_due' fields in contexts where they're not applicable, eg when the 'update' is the XLoader adding metadata, or just resources being reordered.
- Also fix org and group DCTERMS metadata duplication
- Drop duplicate breadcrumb on resource pages
> [DC-31529][DC-31581][QOL-8842] update ckanext-data-qld to fix validation

- vars/CKAN-Stack.var.yml
- This was applied to 2.8 and upstream 2.10, but was overlooked for 2.9
> [DC-32816] update CKAN fork to patch sqlparse

- .docker/test-OpenData.ini
- .docker/test-Publications.ini
- templates/Datashades-OpsWorks-CKAN-Instances.cfn.yml.j2
- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
By specifying the operating system directly for each instance, rather than just setting a stack default, it will be easier for us to roll forward and back in future. Changing the value will trigger CloudFormation to replace each affected instance.
> QOL-9055 Configure instance operating system directly

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- pyOpenSSL fixes have now been released in v1.4.1, so drop the commit hash and use the tag
> [QOL-9055] update Harvest to use release version

- templates/3_tier_vpc.yml
Also: For NACL, you must not use a rule that already exists since it will keep it till cleanup. i.e. rule 100 exists, so it can't be used till after it is removed
> QOLSVC-1182 split nacl to restrict SSH/RDP all inbound access from 0.0.0.0/0 but allow for local and vpc peering CIDR ranges

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- The new tabulator-based type guessing is much more prone to encountering errors on data that the old system didn't mind. We need to downgrade until those are resolved.
> [QOLSVC-1280] downgrade XLoader to fix type guessing errors

- .docker/test-OpenData.ini
- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- vars/shared-Publications.var.yml
- Update extensions to add CKAN 2.10 support.
- Remove ODI Certificates as it's obsolete and hard to update.
> QOLSVC-978 prepare for CKAN 2.10

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
Previous errors found in upstream have been fixed, we're back on our fork.
This includes a fix for the resource_data page timing out on very large resources.
> QOLDEV-347 update XLoader to prepare for CKAN 2.10 and fix timeouts

- .ahoy.yml
- .docker/test-OpenData.ini
- bin/ckan_cli
- bin/create-test-data-OpenData.sh
- bin/create-test-data.sh
- bin/init-ext.sh
- bin/init.sh
- bin/serve.sh
- bin/test-bdd.sh
- bin/test.sh
- test/features/admin_reporting.feature
- test/features/datarequest.feature
- test/features/dataset_schema.feature
- test/features/engagement_reporting.feature
- test/features/environment.py
- test/features/google_analytics.feature
- test/features/groups.feature
- test/features/resource_align_default_schema.feature
- test/features/resource_availability.feature
- test/features/resources.feature
- test/features/users.feature
- vars/CKAN-Stack.var.yml
- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- Show "HIDDEN" label on resources hidden for privacy reasons, update privacy assessment help text, hide the Request Privacy Assessment field from unprivileged access
- Make data request comments searchable
- Enable Recaptcha bot protection
- Adjust display of missing fields to be "[blank]" instead of a "not in data" message.
- Also prune unnecessary test data and adjust build order to run faster (initialise database while test CKAN instance is starting).
> [CHDEXCHAE-60] update Data theme with enhancements to hidden resources

- vars/CKAN-Stack.var.yml
- Tokens are generated to send emails, then cleaned up afterward, but if they started with '-' the cleanup failed.
> [QOLDEV-517] update cookbook to fix revocation of API tokens

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- Files containing a large number of single and double quotes could be parsed successfully on CKAN 2.9 but fail on CKAN 2.10 due to different parsing behaviour. Fixed by increasing file sample size to match 2.9 behaviour.
> [QOLDEV-424] update XLoader to fix parsing of mixed quotes

- vars/shared-CKANTest.var.yml
- Solr 8 is the standard version for CKAN 2.10+ so we should start testing on it
> [QOLDEV-312] update CKAN 2.10 environment to use Solr 8

- vars/CKAN-Stack.var.yml
- Ensure egg metadata is updated after pulling the target revision, eg to add knowledge of ckanext-activity after updating to CKAN 2.10
- Restore validation badges now that Link Digital's work is in PROD
> [QOLSVC-978] update cookbook

- vars/CKAN-Stack.var.yml
- Solr 8 has index upgrade problems. Solr 7 should be able to work with CKAN 2.10 for now.
> [QOLSVC-978] downgrade to Solr 7

- vars/CKAN-Stack.var.yml
- Solr 8+ will restrict access to directories outside its home.
> [QOLDEV-627] update cookbook to put Solr backups inside Solr home directory

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- 'unicode' validator no longer works in CKAN 2.10
> [QOLDEV-349] update Geoscience harvester to replace obsolete validator

- .ahoy.yml
- bin/create-test-data-OpenData.sh
- bin/process-config.sh
- test/features/comments.feature
- test/features/data_qld_theme.feature
- test/features/datarequest.feature
- test/features/engagement_reporting.feature
- test/features/steps/steps.py
- vars/CKAN-Stack.var.yml
- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- Move customisations from theme to ckanext-datarequests so we don't have to double up on them
> [QOLDEV-638] update Open Data theme and data requests

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- cp-1252 encoding is mostly ASCII, so it can be mistaken for UTF-8 when sampling the file. Add a fallback to try cp-1252 if UTF-8 fails.
> [QOLSVC-2984] update XLoader to better handle Windows encoding

- vars/CKAN-Stack.var.yml
- Don't try to interpret the write lock file as an index segment
- Poll the shared drive to determine when the backup is available, instead of using a fixed wait
> [QOLDEV-653] update cookbook to make Solr replication more robust

- vars/CKAN-Stack.var.yml
- If /user/_logout is cached then it doesn't delete the session cookie
> [QOLDEV-640] update CKAN core to disable caching on logout URL

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- Form structure has changed from CKAN 2.9, so this feature stopped working.
> [QOLSVC-3826] update Open Data theme to hide size field for uploads

- test/features/steps/steps.py
- vars/CKAN-Stack.var.yml
- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- Logging out has side effects so it shouldn't be a GET. Changing to a POST will fix its interactions with caching and CSRF filtering.
> [QOLDEV-640] update CKAN fork to turn logout into a POST

- vars/CKAN-Stack.var.yml
- Config to disable core CSRF was being injected in the wrong place and was ineffective. We have our own filter, which has less false positives
> [QOLSVC-3914] update cookbook to disable core CSRF filter

- test/features/comments.feature
- test/features/steps/steps.py
- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
We have forked the profanityfilter library so we can fix its handling of regex-significant characters, see https://github.com/areebbeigh/profanityfilter/issues/25
> QOLDEV-683 update YTP Comments to fix profanity filter

- check_ext_versions.py
- get_latest_tag.sh
- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- vars/shared-Publications.var.yml
- Fix CKAN 2.10 compatibility
- Only update S3 object visibility if we're updating the dataset or uploading a new file, to reduce churn on background jobs
> [QOLSVC-4214] update S3 Filestore plugin

- vars/CKAN-Stack.var.yml
- CKAN 2.10's caching can sometimes make a page incorrectly appear logged out. This change injects a snippet of JavaScript to detect that we're logged in and offer to reload.
> [QOLSVC-3914] update CKAN fork to detect when logged in

- .ahoy.yml
- .github/workflows/test-staging.yml
- .github/workflows/test.yml
- bin/create-test-data-OpenData.sh
- test/features/reporting.feature
- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
Both QA and Archiver reports (`/report/broken-links` and `/report/openness`) had failures under CKAN 2.10 when an organisation was selected, although the page was intact before that point. Scenario tests are now expanded to cover this case, and the underlying errors are fixed.
> QOLSVC-4217 update QA and Archiver to fix report page errors under CKAN 2.10

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- Add 'Delete datastore' button to remove current datastore
- Adjust loading process to truncate tables when structure is unchanged, instead of dropping and recreating them
- Record guessed types as overrides so they're persistent, unless manually changed
> [QOLSVC-3902] update XLoader

- vars/CKAN-Stack.var.yml
Adapted from work by Eric Soroos. Convert from outer join to subquery for better use of indexing. This cuts load times on large feeds by about 30%.
> [QOLSVC-4446] update CKAN core to improve loading speed of large news feeds

- vars/CKAN-Stack.var.yml
- Click 7 changes the expected syntax to use hyphens in command names instead of underscores
> Update cookbook to fix Click syntax

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- Limit the lock timeout when refreshing a datastore table, so we fail fast instead of deadlocking.
> [QOLSVC-3902] update XLoader to reduce deadlocks

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- Acquire write locks up front when updating resource extras, to avoid deadlock risks
- Retry jobs that fail due to locking problems
> [QOLSVC-3902] update XLoader to improve locking robustness

- templates/Datashades-OpsWorks-CKAN-Stack.cfn.yml
- We manage our own groups, and the default groups cause problems for the export script
See https://old.reddit.com/r/aws/comments/13untfl/aws_opsworks_stacks_migration_to_systems_manager/
> [QOLDEV-545] disable default OpsWorks security groups

- vars/CKAN-Stack.var.yml
- Fall back to default 'dataset' type when custom type fails
> [QOLDEV-727] update CKAN core to fix trash page

- templates/Datashades-OpsWorks-CKAN-Stack.cfn.yml
- Putting more information in tags will make our cookbook less reliant on OpsWorks features
> [QOLDEV-545] tag instances with the name of the layer they're in

- templates/Datashades-OpsWorks-CKAN-Stack.cfn.yml
- This will allow the cookbook to populate the CKAN site URL without depending on OpsWorks app definitions. It's more appropriate anyway since the domain is not specific to each plugin.
> [QOLDEV-545] provide the site URL via Chef custom JSON

- templates/Datashades-OpsWorks-CKAN-Stack.cfn.yml.j2
- Cookbook expects 'revision' not 'version', to match the names used by OpsWorks apps
> [QOLDEV-545] fix app source parameter name

- templates/Datashades-OpsWorks-CKAN-Stack.cfn.yml.j2
- templates/cache.cfn.yml
Stop passing parameters that are unused or retrieved from SSM.
> QOLDEV-545 drop unnecessary cookbook parameters

- .ahoy.yml
- chef-deploy.sh
- test/features/resources.feature
- Automatically deregister instances from load balancers during non-parallel deployments
- Add support for executing multiple recipes at once, eg setup + deploy
> [QOLDEV-545] add capabilities to Chef deployment script

- vars/CKAN-Stack.var.yml
- Move CKAN-specific stored parameters to a separate recipe so Solr doesn't try to load them
- Recognise any truthy value for the 'dsenable' parameter
> [QOLDEV-545] update cookbook to fix deployment errors

- templates/Datashades-OpsWorks-CKAN-Stack.cfn.yml.j2
- templates/chef.json.j2
- vars/CKAN-Stack.var.yml
- Add SSM Parameter Store entries for each value, so that servers can retrieve them without needing any extra input. The server tags should provide enough information to locate the parameter values.
- Drop custom JSON in OpsWorks stack (to keep template size within the limit).
- Fix site title to include 'Queensland Government'.
> [QOLDEV-545] replace OpsWorks custom JSON with SSM parameters

- templates/Datashades-OpsWorks-CKAN-Stack.cfn.yml.j2
- templates/hosted-zone.cfn.yml
- Previously added as an app-specific parameter, which is unnecessary duplication and complications the permissions.
> [QOLDEV-818] add hosted zone to Parameter Store as a shared parameter

- templates/hosted-zone.cfn.yml
- 'Name' isn't an exported property of HostedZone
> [QOLDEV-818] specify zone name manually

- templates/Datashades-OpsWorks-CKAN-Stack.cfn.yml.j2
- vars/CKAN-Stack.var.yml
- Make shutdown actions occur without needing OpsWorks
- Use instance ID to assemble hostname
- Allow calls to the Grants stored database procedure
> [QOLDEV-818] update cookbook

- chef-deploy.sh
- files/instanceSetupLambda.js
The existing deployment procedure, deregistering instances from the load balancer and then running a setup command on them, is suitable for OpsWorks servers, but not for autoscaling groups using the load balancer to detect unhealthy servers that need to be replaced.
Instead, run an instance refresh command on the autoscaling group to replace instances with new ones.
> QOLDEV-819 adjust deployment to handle OpsWorks instances separately from autoscaling groups

- chef-deploy.sh
- This can occur if eg a load-scaled instance was running at the start of the deployment but stopped during deployment to another server
> [QOLDEV-819] skip deploying to instances that are no longer running

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- Allow 15 seconds, instead of 5 (because 5 might be triggered by mere slowness)
> [QOLSVC-3902] update XLoader to slightly increase deadlock timeouts

- chef-deploy.sh
- templates/Datashades-OpsWorks-CKAN-Instances.cfn.yml.j2
- vars/instances-CKANTest.var.yml
- vars/instances-OpenData.var.yml
- vars/instances-Publications.var.yml
- Put instances into standby before deploying to them, instead of launching an instance refresh. This should be faster as we don't need to recreate machines from scratch every time.
- Adjust minimum autoscaling sizes to allow instances to go into standby.
> QOLDEV-819 refine autoscaling deployments

- build-CKAN.sh
- templates/Datashades-OpsWorks-CKAN-Stack.cfn.yml.j2
- Add permission to send logs to S3 bucket
- Combine permissions that apply to all instances into one policy, so we remain under the 10-per-role limit
> QOLDEV-818 fix instance permissions

- templates/Datashades-OpsWorks-CKAN-Instances.cfn.yml.j2
- Shorten the grace period for Solr instance startup since it doesn't need as long as CKAN instances
- Set the desired capacity (along with max and min) during power management actions
> QOLDEV-819 clean up scaling config

- templates/Datashades-OpsWorks-CKAN-Instances.cfn.yml.j2
- Recreating Solr instances doesn't preserve the index. TODO Fix index sync so new instances can pick up the latest index.
> [QOLDEV-819] exclude Solr instances from power management

- README.md
- templates/Datashades-OpsWorks-CKAN-Extensions.cfn.yml.j2
- templates/Datashades-OpsWorks-CKAN-Instances.cfn.yml.j2
- templates/Datashades-OpsWorks-CKAN-Stack.cfn.yml.j2
- templates/hosted-zone.cfn.yml
- vars/CKAN-Stack.var.yml
- Can't rename CloudFormation stacks at this point, or else they will be deleted and recreated, which would be unnecessarily disruptive
> [QOLDEV-839] drop OpsWorks resources (stack and layers) and documentation references

- build-CKAN.sh
- chef-deploy.sh
- templates/Datashades-OpsWorks-CKAN-Instances.cfn.yml.j2
- vars/instances-CKANTest.var.yml
- vars/instances-OpenData.var.yml
- vars/instances-Publications.var.yml
- If current capacity is at the minimum, then don't reduce it further when putting an instance in standby.
- Increase minimum capacity configuration to reflect new behaviour.
> QOLDEV-867 make deployments handle autoscaling more robustly

- templates/Datashades-OpsWorks-CKAN-Stack.cfn.yml.j2
- templates/cloudfront.cfn.yml.j2
- templates/waf_web_acl.cfn.yml
- vars/cloudfront.var.yml
- vars/waf_web_acl.var.yml
- WAFv2 resources are required to be in the us-east-1 region, but CloudFormation exports cannot cross regions, so use the SSM Parameter Store to pass necessary values.
> [QOLDEV-908] move WAF stack to global region

- files/instanceSetupLambda.js
- vars/CKAN-Stack.var.yml
- Limit datastore_delete to waiting 20 seconds for a lock to drop the table. The actual drop can take longer, but if we can't acquire a lock in a timely manner, we should avoid deadlock by cancelling
> [QOLSVC-6752] update CKAN core to reduce datastore deadlocks

- vars/CKAN-Stack.var.yml
- Need to use dependencies that can handle IMDS v2, which is required by default on newer Amazon Linux
> [QOLSVC-6955] update cookbook to use newer SMTP relay

- chef-deploy.sh
- If any instance is on the wrong launch template version, run an instance refresh instead of a regular deployment.
- TODO Use SkipMatching flag to reduce the refresh scope once Bamboo is on newer AWS CLI
> [QOLDEV-920] replace instances with obsolete launch templates during deployment

- chef-deploy.sh
- By putting instances into standby we don't need to interact with the load balancer directly.
- Batch and Solr layers should be included in instance refresh if they have become outdated.
> [QOLDEV-920] drop load balancer requirement for instance refreshes

- templates/database.cfn.yml
- Names must be unique, so when upgrading the major database version, which creates the new database before deleting the old, we need to use a different name
> [QOLSVC-7171] include DB version in RDS parameter group name

- templates/Datashades-OpsWorks-CKAN-Instances.cfn.yml.j2
- Expanding Solr index results in larger backups, production is getting full
> [QOLSVC-7469] increase size of Solr secondary disk

- templates/Datashades-OpsWorks-CKAN-Stack.cfn.yml.j2
- vars/CKAN-Stack.var.yml
- Currently we use a config file that tries to provide a mapping for every environment based on hostname, which is inelegant and fragile.
> [QOLDEV-933] add SSM Parameter Store entry for PURL endpoint

- templates/database.cfn.yml
- Our Chef runs don't currently handle SSL connections to the database.
- PostgreSQL 15+ forces SSL by default.
> [QOLSVC-7171] disable database SSL requirement

- templates/database.cfn.yml
- vars/database.var.yml
[fix: QOLDEV-989 disable Parallel Workers Per Gather when vCPU is less than 4](https://github.com/qld-gov-au/ckan-qld-infrastructure/commit/cbe76985999b67f272464765413aa283600d9fc3) 
To stop IPC: MessageQueueSend waits on:
SELECT activity.id AS activity_id, activity.timestamp AS activity_timestamp, activity.user_id AS activity_user_id, activity.object_id AS activity_object_id, activity.revision_id AS activity_revision_id, activity.activity_type AS activity_activity_type
FROM activity
WHERE activity.object_id IN (SELECT package.id
FROM package
WHERE package.private = false AND package.owner_org = '1d443ba7-8efb-42f0-b836-9be70390378d' UNION SELECT '1d443ba7-8efb-42f0-b836-9be70390378d' AS anon_1) AND (activity.user_id NOT IN ('cefefdab-2536-436b-b34c-75252b2e2c0e')) ORDER BY …
> FIX: QOLDEV-989 fix max_parallel_workers_per_gather to 0 when vCPU less than 4

- AMI-templates.yml
- build-CKAN.sh
- create-AMI.yml
- inventory/hosts
- templates/AMI-Template-Instances.cfn.yml.j2
- templates/Datashades-OpsWorks-CKAN-Instances.cfn.yml.j2
- templates/Datashades-OpsWorks-CKAN-Stack.cfn.yml.j2
- vars/AMI-template-instances.var.yml
- vars/CKAN-Stack.var.yml
- vars/instances-CKANTest.var.yml
- vars/instances-OpenData.var.yml
- vars/instances-Publications.var.yml
Prepare instances to a "cold standby" state and generate machine images from them, then apply those images to the autoscaling groups.
This should give us dramatically improved server start and failover times, as well as reducing the risk of failures resulting from upstream dependency changes (because dependency installation takes place during the deployment, when the image is created, not when each server is started).
> QOLDEV-833 Run autoscaling groups on custom AMIs

- build-CKAN.sh
- create-AMI.yml
- Fix SSM parameter so baseline AMIs can be automatically updated
- Allow deployments to recognise when an AMI already exists and doesn't need to be generated.
> QOLDEV-833 improve autoscaling AMI handling

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- Add CKAN 2.11 testing and drop 2.8 support
- Use PyPI for profanityfilter instead of source install
- We now own the primary fork, so we can use standard version numbering
> [QOLDEV-1009] update YTP Comments

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- vars/shared-Publications.var.yml
CKAN 2.10 added a class to the main 'div' tag, which was not reflected in our themes, resulting in mobile navigation menus appearing above the content.
> QOLSVC-8437 fix mobile navigation menu position

- build-CKAN.sh
The logic to detect existing images and skip image creation was not actually configuring the autoscaling groups to _use_ the existing image IDs.
> [QOLDEV-833] ensure existing image IDs are applied to the ASG when found

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- Ensure that the 'url_type' field treats "None" the same as literal None.
- Also merge upstream changes to keep our fork in sync.
> [QOLSVC-8504] update XLoader to fix missing Datastore button

- create-AMI.yml
Fix search syntax so we correctly identify the setup command and determine when the template instance is ready. Previously it was sometimes latching onto the wrong command.
> QOLDEV-833 fix AMI creation

- test/features/steps/steps.py
- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- vars/shared-Publications.var.yml
- Handle change of Webassets code structure
- Handle new schema definition for password resets
- Don't override the login failure message if CAPTCHA is not enabled
- Drop Python 2 support
- Handle deprecation of 'webstore_url' field
> [QOLDEV-955] update shared QGOV plugin

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- Fix 'package_show' parameter to use 'id' rather than the broken fallback 'name_or_id'
> [QOLDEV-1020] update Resource Visibility plugin for CKAN 2.11

- vars/CKAN-Stack.var.yml
- drop obsolete Recline-based views
- drop obsolete CSRF filter config
- add batch jobs to refresh reports, Solr index
- ensure plugins have a chance to apply database migrations
> [QOLDEV-954] update cookbook to prepare for CKAN 2.11

- build-CKAN.sh
Template size now exceeds the maximum of 51200 and needs to be split into separate templates. This is a temporary fix to get deployments working.
> Temporarily disable updating security groups due to CloudFormation inline template size limit

- .ahoy.yml
- bin/init-OpenData.sh
- bin/serve.sh
- test/features/schema_generation.feature
- Adjust setup order so database init happens immediately before launching CKAN instance
- Inject the XLoader job token into config during init
> inject XLoader job token into test config

- vars/CKAN-Stack.var.yml
Datastore is not on the list of plugins to install, it's enabled separately. That should happen first, so that ordering can be properly applied.
> [QOLSVC-10616] patch datastore plugin order in cookbook

- vars/shared-CKANTest.var.yml
- vars/shared-OpenData.var.yml
- Update blueprint to match core URL rule, so that versioned API calls such as '/api/3/action/package_show' will be intercepted properly.
> [QOLSVC-10984] update Data theme to fix GA4 URL rules

- inventory/hosts
- templates/AMI-Template-Instances.cfn.yml.j2
from
ami-034488765f896f58f: Amazon Linux 2023 AMI 2023.6.20250317.2 x86_64 HVM kernel-6.1
to
ami-0059ed5a3aacdfe15: Amazon Linux 2023 AMI 2023.8.20250915.0 x86_64 HVM kernel-6.1
> Upgrade base ami to Amazon Linux 2023 AMI 2023.8.20250915.0
